### PR TITLE
Fix mesh csgraph distances

### PR DESCRIPTION
**Pull request by ceesem**
mesh.csgraph had weights that were typically twice that of the distance between vertices, due to double counting the bidirectional edges between vertices on a face. This PR fixes that by turning off the double counting (i.e. setting directed=True in `create_csgraph`) and making link_edges similarly bidirectional when they count toward graph_edges. To avoid double counting, I also check that make sure that the naive bidirectional link_edges doesn't have duplicate edges when used to make the csgraph.

### CODE REVIEW

**Comment by ceesem** [comment]
I'll look into the test results shortly...

**Comment by fcollman** [comment]
Looks like it is just a change in Skeleton behavior... not clear which is better. It’s an interesting difference favoring short mesh hops

**Comment by ceesem** [comment]
A bit unclear about what changed since tests were written, but the existing branch points look totally right on inspection of the skeletonization and the current full_cell_with_ais.png output is slightly rotated relative to the file that was in there before. Tests pass now and the results look good to me.

**Comment by ceesem** [comment]
I'm going to close this as a PR into master and re-open it as a PR into fcc_skel_quality, since the scope has changed a bit due to usage needs.

**Pull request closed without merging**
