### PR TITLE
Fix downloads

### PR DESCRIPTION
**Pull request by ceesem**
Changes in https://github.com/sdorkenw/MeshParty/commit/2390853beccddf610ac03e1a33fa8152e7523e4b#diff-adba6b5f73a0b259a36b14a2cf31a931 broke mesh downloading for graphene mesh data sources and only worked for precomputed meshes. This fix checks the cloudvolume path to see if it's graphene or not (based on the graphene:// initial part of the string) and reverts to the previous method if so and the other method if not.

More generally, this brings up a problem in the incompatibility between the mesh.get call for Precomputed vs Graphene datasources in cloudvolume. There should be some a validation check to assert that they have matched and standardized APIs.

### CODE REVIEW

**Comment by fcollman** [comment]
@william-silversmith an FYI and something to consider for cloudvolume

**Comment by william-silversmith** [comment]
Initially, I wanted to let different plugins have their own behaviors, but unless there's a functionality issue, we should probably make them match as closely as possible.

**Comment by ceesem** [comment]
Yeah, from the user perspective the sources shouldn’t be different, at least within meshparty. The easiest way is if the cloudvolume get interface is the same, but at a minimum no user-facing code should care if something is graphing or precomputed or whatever else.

**Comment by william-silversmith** [comment]
It's tricky for there to be zero differences because they have different features. However, for basic usage, I agree that shared invocations are possible.

https://github.com/seung-lab/cloud-volume/issues/268

**Pull request merged**
